apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cpt-stack
spec:
  project: default
  source:
    repoURL: 'https://github.com/craftbrak/Clever-Party-Thrower'
    path: kubeconfigs/front-end
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}